### ISSUE TITLE
regex incorrect; gives false negative error

### ISSUE THREAD

**Issue by michaelchadwick** [trappar/hyperlightdrifter-transfer#1]
I tried using your tool to transfer my Windows save to a Mac, but it gave me an error. Digging into the code, it looks like the regex for that one consistent bit of data amongst all saves is a bit too greedy. The only pertinent bit is `eyAi`, and if you try to match further right it gives a false negative error because it doesn't find the rest of the string in certain save files, failing to finish the conversion.

I did the copy/paste by hand and it worked, so unless I'm some edge case, this tool may be failing for others, as well.

Thanks for the awesome tool!

**Comment by trappar** [comment]
Sounds like you have a pretty good idea of what's going on. Want to fix it? 😄

I'll look into it at some point but if you wanted to open a pull request that would be awesome!

**Comment by michaelchadwick** [comment]
No problem. I will give it a whirl later today.

**Comment by trappar** [comment]
Fixed by https://github.com/trappar/hyperlightdrifter-transfer/pull/2

Thanks!
